Add gitignore.
Tino-FRC-2473/FRC2018-Offseason pull request #5
Opened 2018-12-14 04:53 UTC by mlucas

This resolves https://github.com/Tino-FRC-2473/FRC2018-Offseason/issues/4.

2018-12-15 00:08 UTC, tnarayanan requested changes
Some of the file extensions will not be used at all, so they do not need to be in the gitignore.

2018-12-15 00:08 UTC, tnarayanan commented on .gitignore
> +*.ctxt
Not relevant because we are not using BlueJ

2018-12-15 00:08 UTC, tnarayanan commented on .gitignore
> +.mtj.tmp/
We are not using Mobile Tools for Java, so this is not necessary

2018-12-17 04:57 UTC, mvoodarla approved these changes
I removed a few things that I thought were unnecessary so I think it's good to commit. We now need to remove all the files in the gitignore that have already been committed.

2018-12-17 22:50 UTC, tnarayanan approved these changes

2018-12-21 05:02 UTC, merged